"""Coding Agent - generates, refactors, explains, and fixes code."""

from __future__ import annotations

from typing import Any

from agentforge_agents.core.base import BaseAgent
from agentforge_agents.schemas.common import Message
from agentforge_agents.schemas.planning import PlannerResponse
from agentforge_agents.schemas.task import TaskRequest, TaskResult
from agentforge_agents.utils.logging import get_logger

log = get_logger(__name__)


class Agent(BaseAgent):
    """Handles code generation, refactoring, explanation, and bug fixes.

    Invokes the configured model to produce code. When a ``verify`` flag or the
    ``run_tests`` mode is requested, tool calls are used to execute the result.
    """

    @property
    def default_tools(self) -> list[str]:
        return [
            "filesystem",
            "terminal",
            "python_runner",
            "git",
            "docker",
            "sql",
            "github",
            "search",
            "http",
        ]

    async def plan(self, request: TaskRequest) -> PlannerResponse:
        return self._simple_plan(request, "coding")

    async def execute(self, request: TaskRequest) -> TaskResult:
        instructions = request.instructions or request.text_input()
        mode = request.input.get("mode", "generate") if request.input else "generate"
        if self.config.model.provider == "mock" and mode != "explain":
            return TaskResult.success(
                request.task_id,
                {
                    "language": request.input.get("language", "python"),
                    "mode": mode,
                    "code": _mock_code(instructions),
                },
                agent_id=self.agent_id,
            )

        language = request.input.get("language", "python") if request.input else "python"
        system = self.config.system_prompt or "You are the Coding Agent."
        messages = [
            Message.system(system),
            Message.user(f"Mode: {mode}\nLanguage: {language}\n\nTask:\n{instructions}"),
        ]
        code = await self._generate_text(messages)

        if mode in {"verify", "execute"}:
            verification = await self._verify_code(code, language)
            return TaskResult.success(
                request.task_id,
                {"mode": mode, "language": language, "code": code, "verification": verification},
                agent_id=self.agent_id,
            )
        return TaskResult.success(
            request.task_id,
            {"mode": mode, "language": language, "code": code},
            agent_id=self.agent_id,
        )

    async def _verify_code(self, code: str, language: str) -> dict[str, Any]:
        if language == "python":
            result = await self._call_tool("python_runner", {"code": code})
            return {
                "tool": "python_runner",
                "success": result.success,
                "output": result.output,
                "error": result.error,
            }
        return {
            "tool": "none",
            "success": True,
            "output": "verification requires a corresponding runner for this language",
            "error": None,
        }

    async def stream(self, request: TaskRequest):
        from agentforge_agents.schemas.events import EventType, ExecutionEvent

        result = await self.execute(request)
        code = (
            str(result.output.get("code", ""))
            if isinstance(result.output, dict)
            else str(result.output)
        )
        chunk_size = 64
        total = max(len(code), 1)
        for start in range(0, len(code), chunk_size):
            yield ExecutionEvent.create(
                EventType.TASK_PROGRESS,
                task_id=request.task_id,
                agent_id=self.agent_id,
                session_id=self.context.session_id,
                payload={
                    "progress": min(1.0, (start + chunk_size) / total),
                    "delta": code[start : start + chunk_size],
                },
            )
        yield ExecutionEvent.create(
            EventType.TASK_COMPLETED,
            task_id=request.task_id,
            agent_id=self.agent_id,
            session_id=self.context.session_id,
            payload={
                "result": (
                    result.model_dump()
                    if hasattr(result, "model_dump")
                    else {"output": result.output}
                )
            },
        )


def _mock_code(instructions: str) -> str:
    return (
        "# Generated by the coding agent (mock mode).\n"
        f"# Task: {instructions[:200]}\n"
        "def solve():\n"
        "    return 'mock implementation'\n"
    )


__all__ = ["Agent"]
